version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: mygo_postgres
    environment:
      POSTGRES_USER: mygo
      POSTGRES_PASSWORD: mygo
    volumes:
      - mygo:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

volumes:
  mygo: