// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/snoeffels/mygo/controllers"
	"github.com/snoeffels/mygo/repositories"
	"github.com/snoeffels/mygo/services"
	"gorm.io/gorm"
)

import (
	_ "github.com/snoeffels/mygo/docs"
)

// Injectors from wire.go:

func initTodoAPI(db *gorm.DB) controllers.TodoAPI {
	todoRepository := repositories.ProvideTodoRepository(db)
	todoService := services.ProvideTodoService(todoRepository)
	todoAPI := controllers.ProvideTodoAPI(todoService)
	return todoAPI
}
