// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/snoeffels/mygo/api"
	"github.com/snoeffels/mygo/persistence"
	"gorm.io/gorm"
)

import (
	_ "github.com/google/subcommands"
	_ "github.com/snoeffels/mygo/docs"
)

// Injectors from wire.go:

func initTodoAPI(db *gorm.DB) api.TodoController {
	todoRepository := persistence.ProvideTodoRepository(db)
	todoService := persistence.ProvideTodoService(todoRepository)
	todoController := api.ProvideTodoAPI(todoService)
	return todoController
}
